name: computable_reals
description: Computable reals, or constructive real numbers in Dart. Approximates real numbers to arbitrary precision.
version: 1.0.0
repository: https://github.com/aarol/computable_reals
issue_tracker: https://github.com/aarol/computable_reals/issues

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
